### ISSUE TITLE
[Enhancement] Add a command to display the path to the current venv

### ISSUE THREAD

**Issue by b-morgan** [OctoPrint/venv-tool#1]
In this [topic](https://community.octoprint.org/t/problem-upgrading-octorelay/61195/14) user [mich0111](https://community.octoprint.org/u/mich0111) writes:

Unfortunately, I don't know what to replace the paths with to run this command:
`octoprint-venv-tool recreate-venv /path/to/your/venv --python /path/to/python`

The path to python can be determined with `which python` but the path to the current venv isn't obvious to me (or mich01111).

If there was a command in venv-tool to display the path to the current venv this would make things easier. 

Even better would be one that listed "all" the virtual environments it could find and "all" the python versions it could find.

If there is already a way to determine the current venv, then perhaps just adding some help text would be sufficient.

**Comment by foosel** [comment]
That's something I'd rather tackle via the FAQ and/or README, if needed. The idea behind this tool is to allow the user to fix things on *any* OctoPrint setup (not just OctoPi where the venv location is known). It's impossible to find all possible venvs, and it would cause tons of issues if I'd show the user a list and they'd decided on the wrong one and killed it that way. 

There's a reason why the [FAQ](https://community.octoprint.org/t/octoprint-tells-me-my-python-environment-is-outdated-and-will-soon-no-longer-be-supported-how-do-i-upgrade/61076) tells people to rather reinstall OctoPi - it really is way easier than using the tool, and especially on OctoPi the tool will often not help as there won't be a newer Python version available.

I'm fine with the community using the tool in additional tooling built around it, or tutorials or whatnot, but I won't try to make it more (pseudo-)intelligent than it needs to be, as that will cause more problems down the road if used by people who don't know what they are doing.
